Recipe book
jcderry5/hci-recipe-app pull request #19
Opened 2023-04-05 16:43 UTC by Emdorkable

old fb, wait 10-15 seconds after adding a recipe to refresh

2023-04-05 17:38 UTC, willeng37 commented
I think the only issues that probably need to be checked are rendering errors due to a null (non-logged in) user for any protected pages.

2023-04-05 22:25 UTC, danthynguyen requested changes, later dismissed
the recipes are not rendering on the recipe book page

there is an uncaught promise in RecipeBook.js 44:1, looks like its trying to convert an undefined or null into an object

![image](https://user-images.githubusercontent.com/73391187/230225032-606d96ec-a170-4078-aebb-88515a3d6570.png)

I think there might be something wrong with the fetch in the function

2023-04-05 22:32 UTC, danthynguyen approved these changes
list of issues to address later
- only renders on refresh on first time
- when reaccessing the recipe book, takes 5 seconds to render, otherwise looking at a blank page
- memory-wasting on firebase

2023-04-06 15:35 UTC, jcderry5 approved these changes
LGTM

2023-04-06 15:35 UTC, jcderry5 commented on src/components/NewRecipe.js
> +            changeAddedIngredients={changeAddedIngredients}
remove changeAddedIngredients :)

2023-04-06 16:35 UTC, jcderry5 approved these changes
Trusting Will

2023-04-06 16:36 UTC, merged